# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8b59e8e64f7417292294ab2db0aa0b0be7ef249593513cec9dc4cb0ba6a2820b73795c6b1eea0c1b7067ee70891e6fa994208eaaaab957f2018029668b50a58

test:
  secret_key_base: 918aa6af8d57481205a2f0af5ae4456c8206197ad08db0cb61a47b7d0309ca1570935e27cce40f5ae36bf08b784aed2af3568c0e1a90f335b6de02e38379911b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
